### ISSUE TITLE
nools-ts

### ISSUE THREAD

**Issue by datasmithtech** [emreeren/pmpos3#1]
hi,
I am interested in following how you got nools-ts to work.

Where may I find your calls to nools-ts?

My target technology stack is angular 6 application which runs on typescript.

**Comment by emreeren** [comment]
Initialization:
https://github.com/SambaDNA/sambadna-core/blob/master/src/RuleManager/index.ts#L57

Usage:
https://github.com/SambaDNA/sambadna-core/blob/master/src/RuleManager/index.ts#L98
